# Auto-generated OpenRCX SPEF extraction for blk (Sky130)
# Generated by coresmith backend_helpers.generate_rcx_tcl

set script_dir [file dirname [file normalize [info script]]]

set tech_lef   "@@TECH_LEF@@"
set cell_lef   "@@CELL_LEF@@"
set liberty    "@@LIBERTY@@"
set sdc_file   "@@SDC@@"
set def_file   "@@DEF@@"
set rcx_rules  "@@RCX_RULES@@"
set out_dir    "$script_dir"

puts "========== RCX SPEF Extraction: blk =========="

# 1. Read design from DEF
read_lef $tech_lef
read_lef $cell_lef
read_liberty $liberty
read_def $def_file
read_sdc $sdc_file

set_propagated_clock [all_clocks]

# 2. Set via resistances (Sky130 calibration from OpenROAD-flow-scripts)
set tech [ord::get_db_tech]
[$tech findLayer mcon] setResistance 9.249146
[$tech findLayer via]  setResistance 4.5
[$tech findLayer via2] setResistance 3.368786
[$tech findLayer via3] setResistance 0.376635
[$tech findLayer via4] setResistance 0.00580

# 3. Run OpenRCX extraction
puts "Running OpenRCX extraction..."
define_process_corner -ext_model_index 0 X
extract_parasitics -ext_model_file $rcx_rules

# 4. Write SPEF
puts "Writing SPEF..."
write_spef "$out_dir/blk.spef"

# 5. Write power-aware Verilog for LVS
write_verilog -include_pwr_gnd "$out_dir/blk_pwr.v"

# 6. Post-extraction STA
puts "\n========== Post-extraction STA =========="
report_checks -path_delay max -format full_clock_expanded
report_checks -path_delay min -format full_clock_expanded
report_tns
report_wns
report_power

puts "\nSPEF: $out_dir/blk.spef"
puts "Power Verilog: $out_dir/blk_pwr.v"
puts "Done."

exit
