# Auto-generated wrapper-level PnR for OpenFrame (Sky130)
# Generated by coresmith tapeout_helpers

set script_dir [file dirname [file normalize [info script]]]
set out_dir "$script_dir"

# ---- Read PDK ----
read_lef "@@TECH_LEF@@"
read_lef "@@CELL_LEF@@"
read_liberty "@@LIBERTY@@"

# ---- Read wrapper netlist (flattened, includes block logic) ----
read_verilog "@@WRAP_NETLIST@@"
link_design openframe_project_wrapper
read_sdc "@@OUT_DIR@@/wrapper.sdc"

# ---- Fixed OpenFrame die ----
initialize_floorplan \
    -die_area "0 0 3520.0 5188.0" \
    -core_area "100.0 100.0 \
                3420.0 \
                5088.0" \
    -site unithd

# Routing tracks
make_tracks li1  -x_offset 0.23 -x_pitch 0.46 -y_offset 0.17 -y_pitch 0.34
make_tracks met1 -x_offset 0.17 -x_pitch 0.34 -y_offset 0.17 -y_pitch 0.34
make_tracks met2 -x_offset 0.23 -x_pitch 0.46 -y_offset 0.23 -y_pitch 0.46
make_tracks met3 -x_offset 0.34 -x_pitch 0.68 -y_offset 0.34 -y_pitch 0.68
make_tracks met4 -x_offset 0.46 -x_pitch 0.92 -y_offset 0.46 -y_pitch 0.92
make_tracks met5 -x_offset 1.70 -x_pitch 3.40 -y_offset 1.70 -y_pitch 3.40

place_pins -hor_layers met3 -ver_layers met2

# ---- PDN (wrapper-level: met4 + met5) ----
add_global_connection -net VPWR -pin_pattern "VPWR" -power
add_global_connection -net VGND -pin_pattern "VGND" -ground
add_global_connection -net VPWR -pin_pattern "VPB" -power
add_global_connection -net VGND -pin_pattern "VNB" -ground
global_connect

set_voltage_domain -name CORE -power VPWR -ground VGND
define_pdn_grid -name wrapper_grid -starts_with POWER -voltage_domain CORE -pins {met4 met5}
add_pdn_stripe -grid wrapper_grid -layer met1 -width 0.48 -followpins -starts_with POWER
add_pdn_stripe -grid wrapper_grid -layer met4 -width 1.6 -pitch 27.14 -offset 13.57 -starts_with POWER
add_pdn_stripe -grid wrapper_grid -layer met5 -width 1.6 -pitch 27.14 -offset 13.57 -starts_with POWER
add_pdn_connect -grid wrapper_grid -layers {met1 met4}
add_pdn_connect -grid wrapper_grid -layers {met4 met5}
pdngen

# ---- Standard cell placement and routing ----
global_placement -density 0.3 -pad_left 2 -pad_right 2
detailed_placement
check_placement -verbose

# Filler / decap cells for continuous n-well and power rail
filler_placement -prefix FILLER {sky130_fd_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__fill_2 sky130_fd_sc_hd__fill_1}

set_wire_rc -signal -layer met2
set_wire_rc -clock  -layer met3

clock_tree_synthesis \
    -buf_list {sky130_fd_sc_hd__clkbuf_4 sky130_fd_sc_hd__clkbuf_8} \
    -root_buf sky130_fd_sc_hd__clkbuf_8 \
    -sink_clustering_enable
set_propagated_clock [all_clocks]
repair_clock_nets
remove_fillers
detailed_placement
filler_placement -prefix FILLER {sky130_fd_sc_hd__decap_12 sky130_fd_sc_hd__decap_8 sky130_fd_sc_hd__decap_6 sky130_fd_sc_hd__decap_4 sky130_fd_sc_hd__decap_3 sky130_fd_sc_hd__fill_2 sky130_fd_sc_hd__fill_1}

set_routing_layers -signal met1-met4 -clock met3-met4
global_route -congestion_iterations 50
detailed_route -output_drc "$out_dir/wrapper_route_drc.rpt" -verbose 1

# ---- Reports ----
report_checks -path_delay max > "$out_dir/wrapper_timing_setup.rpt"
report_checks -path_delay min > "$out_dir/wrapper_timing_hold.rpt"
report_wns > "$out_dir/wrapper_wns.rpt"
report_tns > "$out_dir/wrapper_tns.rpt"
report_power > "$out_dir/wrapper_power.rpt"

puts "\n========== WRAPPER SUMMARY =========="
report_design_area
report_wns
report_tns

# ---- Write outputs ----
write_def "$out_dir/openframe_project_wrapper_routed.def"
write_verilog "$out_dir/openframe_project_wrapper_pnr.v"
write_verilog -include_pwr_gnd "$out_dir/openframe_project_wrapper_pwr.v"

puts "\n========== WRAPPER PNR COMPLETE =========="

exit
