# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Shared fixtures for the recorded-build tests: a project whose shared
architecture stages genuinely hold and whose modules are genuinely ready
(registered uArch spec, bound target, built+smoked reference model row with
the same hash construction as ``model build``, declared model check bound to
the current model digest, worker binding in ``.coresmith/env``), plus the
fake graph helpers that let the REAL compiled block subgraph run without a
model worker or an EDA toolchain. The graph, its routes, its parks, its
persistence and its build bookkeeping are never faked."""
from __future__ import annotations

import json
import os
from pathlib import Path
from unittest.mock import AsyncMock

from orchestrator.harness import targets as T
from orchestrator.state_store import builds as B
from orchestrator.state_store import stages as st
from orchestrator.state_store.project_db import open_project

MODULES = ("tiny", "sink")
EDGE = {"edge_id": "tiny__m_out__to__sink__s_in", "producer_block": "tiny", "producer_port": "m_out",
        "consumer_block": "sink", "consumer_port": "s_in", "handshake_protocol": "axi_stream",
        "data_width_bits": 8}

_PRODUCER_RTL = ("module {name}(input clk, input rst_n, output reg [7:0] m_out);\n"
                 "  always @(posedge clk) if (!rst_n) m_out <= 8'd0; else m_out <= m_out + 8'd1;\nendmodule\n")
_CONSUMER_RTL = ("module {name}(input clk, input rst_n, input [7:0] s_in, output reg [7:0] last);\n"
                 "  always @(posedge clk) if (!rst_n) last <= 8'd0; else last <= s_in;\nendmodule\n")


class _Rtl(dict):
    """Synthesizable RTL per module: the first module of a pair produces the
    stream, the second consumes it; any other name gets the producer shape."""

    def __missing__(self, name):
        return _PRODUCER_RTL.format(name=name)


RTL = _Rtl({"tiny": _PRODUCER_RTL.format(name="tiny"), "sink": _CONSUMER_RTL.format(name="sink")})

SPEC = """# {name} microarchitecture

## 2 Interfaces
one stream edge

## 3 Datapath
a counter

### 4a Invariants
none

## 5 Timing
single cycle

### 6a Budget
PERF-001: 8 cycles per op

## 9 Verification
cocotb
"""

_GATE_ENV_OFF = {
    "CORESMITH_ASSERTION_STAGE": "0",
    "CORESMITH_CONTRACT_CONFORMANCE_GATE": "0",
    "CORESMITH_CONTRACT_PORT_GATE": "0",
    "CORESMITH_GATE_SIM": "0",
    "CORESMITH_STORAGE_PRESYNTH_GATE": "0",
    "CORESMITH_BRANCH_PARITY": "0",
    "CORESMITH_IFDEF_LINT": "0",
    "CORESMITH_MEM_PRICE_GATE": "0",
    "CORESMITH_UARCH_FEASIBILITY_GATE": "0",
    "CORESMITH_INTERRUPT_WAIT_S": "0",
    "CORESMITH_FANOUT": "block",
    "CORESMITH_PPA_GATE": "0",
    "CORESMITH_SKIP_ARCH_WARN": "1",
}


def write_env(root: Path, lines: dict[str, str]) -> Path:
    p = root / ".coresmith" / "env"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("".join(f"{k}={v}\n" for k, v in lines.items()))
    return p


def record_model_build(db, root: Path, module: str, *, build_ok: bool = True, smoke_ok: bool = True) -> None:
    """A ``models`` row exactly as ``coresmith model build`` records it: the
    implementation's sha16 and the digest over it with its included headers."""
    ident = B.model_identity(root, module, db)
    db.upsert_model(module, path=ident["path"], sha=ident["sha16"], deps_sha=ident["deps_sha256"],
                    spec_contract_version=str(db.block_contract_version(module)), build_ok=build_ok, smoke_ok=smoke_ok)


def shared_stages_done(db, owner: str) -> None:
    """The structural content ``requirements`` and ``decomposition`` need so
    their ``done`` rows hold on re-evaluation (a registered PRD KPI covered
    by an FRD must-have with acceptance and priority, owned by ``owner``;
    the block diagram and ERS artifacts). For fixtures that mark the shared
    stages done by hand."""
    db.ensure_db_artifact("prd")
    db.ensure_db_artifact("frd")
    db.upsert_items("prd", [{"id": "KPI-FIX-1", "kind": "KPI", "text": "fixture KPI", "priority": "must_have",
                             "acceptance": "fixture"}])
    db.upsert_items("frd", [{"id": "FUNC-FIX-1", "kind": "FUNC", "text": "fixture requirement", "priority": "must_have",
                             "acceptance": "fixture"}])
    db.link_items("FUNC-FIX-1", "KPI-FIX-1", "derives_from")
    db.link_items("FUNC-FIX-1", f"block:{owner}", "owned_by")
    db.ensure_db_artifact("block_diagram")
    db.ensure_db_artifact("ers")


def add_primitive(db, root: Path, name: str = "fab") -> None:
    """An engine primitive (a fabric) appended to the registered block
    diagram; its RTL, testbench and spec are generated by its build."""
    blocks = db.block_diagram()["blocks"]
    db.import_block_diagram({"blocks": blocks + [{"name": name, "tier": 0, "kind": "primitive", "primitive": "cs_fabric",
                                                  "rtl_target": f"rtl/interconnect/{name}.v"}],
                             "connections": []})


def ready_project(root: Path, monkeypatch, *, modules=MODULES, stage: str = "uarch", with_model: bool = True,
                  with_model_check: bool = True, with_rtl: bool = False) -> object:
    """A project at ``stage`` (``uarch`` active, or ``blocks`` active when
    every module is ready) whose shared stages hold on re-evaluation."""
    root = Path(root)
    monkeypatch.setenv("CORESMITH_PROJECT_ROOT", str(root))
    for k, v in _GATE_ENV_OFF.items():
        monkeypatch.setenv(k, v)
    (root / ".coresmith").mkdir(parents=True, exist_ok=True)
    (root / "rtl").mkdir(exist_ok=True)
    (root / "tb" / "cocotb").mkdir(parents=True, exist_ok=True)
    (root / "arch" / "uarch_specs").mkdir(parents=True, exist_ok=True)
    (root / "model" / "frd_eval").mkdir(parents=True, exist_ok=True)
    (root / "inputs").mkdir(exist_ok=True)
    (root / "inputs" / "task.yaml").write_text("top: soc\ntarget_clock_mhz: 50\n")
    db = open_project(root)
    # --- requirements: PRD KPI covered by an FRD item; acceptance + priority
    db.ensure_db_artifact("prd")
    db.ensure_db_artifact("frd")
    db.upsert_items("prd", [{"id": "KPI-FPS-1", "kind": "KPI", "text": "30 frames per second", "priority": "must_have",
                             "acceptance": ">= 30 fps -- throughput.py"}])
    items = [{"id": "FUNC-001", "kind": "FUNC", "text": "the counter increments", "priority": "must_have",
              "acceptance": "cocotb test_count"},
             {"id": "PERF-001", "kind": "PERF", "text": "cycles per op", "priority": "must_have",
              "acceptance": "<= 100 cycles", "metric": "cycles", "bound_max": 100.0, "unit": "cycles",
              "model_check": "cycle accounting on the reference model" if with_model_check else ""}]
    db.upsert_items("frd", items)
    db.link_items("FUNC-001", "KPI-FPS-1", "derives_from")
    db.link_items("PERF-001", "KPI-FPS-1", "derives_from")
    # --- decomposition: block diagram, ownership, ERS
    db.import_block_diagram({"blocks": [{"name": m, "tier": 1, "rtl_target": f"rtl/{m}.v",
                                         "testbench": f"tb/cocotb/test_{m}.py"} for m in modules],
                             "connections": []})
    db.ensure_db_artifact("block_diagram")
    db.ensure_db_artifact("ers")
    for iid in ("FUNC-001", "PERF-001"):
        db.link_items(iid, f"block:{modules[0]}", "owned_by")
    # the bounded must-have is measured at chip scope (a module build defers
    # it; module-scope FRD targets are exercised by test_module_targets_build)
    db.add_verifier("PERF-001", "chip", entry="test_perf_chip", block=modules[0])
    # --- interfaces: contracts + ABI + VIPs + pins + an elaborated shell snapshot
    edge = dict(EDGE, producer_block=modules[0], consumer_block=modules[1],
                edge_id=f"{modules[0]}__m_out__to__{modules[1]}__s_in")
    db.import_contracts({"contracts": [edge]})
    db.ensure_db_artifact("contracts")
    db.ensure_db_artifact("abi")
    (root / ".coresmith" / "vip_index.json").write_text("{}")
    db.pin_add({"name": "clk", "dir": "in", "width": 1, "kind": "clock"})
    db.pin_add({"name": "rst_n", "dir": "in", "width": 1, "kind": "reset"})
    db.add_integration_snapshot({"tier": "0", "top": "soc", "rtl_path": "rtl/soc.v", "real_blocks": [],
                                 "stub_blocks": list(modules), "wires": 1, "boundary_ports": 2, "elaborated": True,
                                 "boundary": ["clk", "rst_n"]})
    # --- uarch readiness per module
    for m in modules:
        spec = root / "arch" / "uarch_specs" / f"{m}.md"
        spec.write_text(SPEC.format(name=m))
        db.register_artifact(f"uarch:{m}", f"arch/uarch_specs/{m}.md")
        T.bind(root, m, {"top": m, "sources": [f"rtl/{m}.v"], "cwd": "."})
        if with_rtl:
            text = RTL[m] if m in RTL else (_CONSUMER_RTL if m == modules[1] else _PRODUCER_RTL).format(name=m)
            (root / "rtl" / f"{m}.v").write_text(text)
        if with_model:
            cpp = root / "model" / f"{m}_model.cpp"
            cpp.write_text(f"// reference model of {m}\n#include \"{m}_model.h\"\nint {m}_model_marker = 1;\n")
            (root / "model" / f"{m}_model.h").write_text(f"// header of {m}\n")
            record_model_build(db, root, m)
    db.link_items(f"uarch:{modules[0]}", "PERF-001", "cites")
    (root / "model" / "frd_eval" / "frd_eval.cpp").write_text("// harness\n")
    if with_model and with_model_check:
        db.add_check("PERF-001", "model_eval", None, value=50.0, sha=B.model_check_sha(db, root, "PERF-001"),
                     actor="frd_eval")
    write_env(root, {"CORESMITH_LLM_PROVIDER": "claude", "CORESMITH_MODEL": "claude-test-model"})
    # --- stage rows
    done_until = st.STAGES.index(stage)
    for i, s in enumerate(st.STAGES[:done_until]):
        db.stage_set(s, i, "done")
    db.stage_set(stage, done_until, "active")
    assert st.current(db) == stage
    return db


ACCEPTANCE_TB = '''import cocotb

from orchestrator.harness import measure


@cocotb.test()
async def test_count(dut):
    """FUNC-001: the counter increments (the Architect's acceptance test)."""
    assert True


@cocotb.test()
async def test_throughput(dut):
    """PERF-{M}-1: cycles per op on the reference workload."""
    measure.record("PERF-{M}-1", 3.0, unit="cycles/op", test="test_throughput")
'''


def add_module_targets(db, root: Path, module: str = "tiny", *, throughput: bool = True, area: bool = True,
                       power: bool = False, functional: bool = True, tb: bool = True) -> dict:
    """FRD targets owned by ``module`` and bound for its build: a throughput
    target measured by the Architect's acceptance test, a std-cell area target
    measured by synthesis, optionally a power target (OpenSTA), and the
    functional FUNC-001 bound to its acceptance test. Returns the ids."""
    root = Path(root)
    m = module.upper()
    tb_rel = f"tb/cocotb/test_{module}.py"
    if tb:
        (root / tb_rel).parent.mkdir(parents=True, exist_ok=True)
        (root / tb_rel).write_text(ACCEPTANCE_TB.replace("{M}", m))
    ids = {}
    items = []
    if throughput:
        ids["perf"] = f"PERF-{m}-1"
        items.append({"id": ids["perf"], "kind": "PERF", "text": f"{module} sustains one op per 4 cycles",
                      "priority": "must_have", "acceptance": "test_throughput <= 4 cycles/op",
                      "metric": "cycles_per_op", "bound_max": 4.0, "unit": "cycles/op"})
    if area:
        ids["area"] = f"AREA-{m}-1"
        items.append({"id": ids["area"], "kind": "AREA", "text": f"{module} standard-cell area", "priority": "must_have",
                      "acceptance": "area_um2 <= 100", "metric": "area_um2", "bound_max": 100.0, "unit": "um2"})
    if power:
        ids["power"] = f"PWR-{m}-1"
        items.append({"id": ids["power"], "kind": "PWR", "text": f"{module} power at the build clock",
                      "priority": "must_have", "acceptance": "power_mw <= 5", "metric": "power_mw", "bound_max": 5.0,
                      "unit": "mW"})
    for it in items:
        db.upsert_item("frd", it)
        db.link_items(it["id"], f"block:{module}", "owned_by")
        db.link_items(it["id"], "KPI-FPS-1", "derives_from")
    if throughput:
        db.add_verifier(ids["perf"], "cocotb", path=tb_rel, entry="test_throughput", block=module,
                        args={"workload": "reference-burst"})
    if area:
        db.add_verifier(ids["area"], "eda", entry="area_um2", block=module)
    if power:
        db.add_verifier(ids["power"], "eda", entry="power_mw", block=module, args={"activity": 0.2, "duty": 0.5})
    if functional:
        db.add_verifier("FUNC-001", "cocotb", path=tb_rel, entry="test_count", block=module)
    ids["tb"] = tb_rel
    return ids


def fake_graph_helpers(monkeypatch, root: Path, *, lint_clean: bool = True, sim_pass: bool = True,
                       synth_ok: bool = True, coverage_applicable: bool = True, rtl_text: str | None = None,
                       calls: dict | None = None) -> dict:
    """Fake the model-worker and EDA helpers the block subgraph calls; the
    graph nodes, routes, parks and persistence stay real. ``calls`` counts
    which helpers ran (a refused build must leave it empty)."""
    from orchestrator.langgraph import pipeline_graph as pg
    counts = calls if calls is not None else {}

    def _hit(name):
        counts[name] = counts.get(name, 0) + 1

    async def fake_generate_rtl(block, attempt, callbacks=None):
        _hit("generate_rtl")
        name = block["name"]
        p = Path(root) / "rtl" / f"{name}.v"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(rtl_text if rtl_text is not None else RTL.get(name, f"module {name}(); endmodule\n"))
        return {"rtl_path": str(p), "verilog": p.read_text()}

    def fake_lint(rtl_path, block_name, attempt=1, **kw):
        _hit("lint_rtl")
        return {"clean": True, "warnings": ""} if lint_clean else {"clean": False, "errors": "syntax error line 1", "log_path": ""}

    async def fake_generate_tb(block, callbacks=None):
        _hit("generate_testbench")
        p = Path(root) / block.get("testbench", f"tb/cocotb/test_{block['name']}.py")
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text("import cocotb\n\n@cocotb.test()\nasync def test_count(dut):\n    assert True\n")
        return {"testbench_path": str(p)}

    def fake_sim(block, rtl_path, tb_path, attempt=1, **kw):
        _hit("run_simulation")
        cov = ({"applicable": True, "pct": 95.0, "floor": 80.0, "points_total": 20, "points_hit": 19,
                "uncovered_count": 1, "passed": True} if coverage_applicable
               else {"applicable": False, "reason": "no verilator_coverage on this host"})
        if sim_pass:
            return {"passed": True, "log": "all tests passed", "returncode": 0, "tests_passed": 1, "tests_total": 1,
                    "tests_failed": 0, "coverage": cov, "throughput": {"applicable": False, "reason": "none declared"},
                    "log_path": ""}
        return {"passed": False, "log": "FAIL: test_count AssertionError", "returncode": 1, "tests_passed": 0,
                "tests_total": 1, "tests_failed": 1, "coverage": cov, "log_path": ""}

    def fake_synth(block, rtl_path, target_clock_mhz=50.0, attempt=1, **kw):
        _hit("synthesize_block")
        if synth_ok:
            return {"success": True, "gate_count": 42, "ff_count": 8, "chip_area_um2": 12.5, "liberty_path": "",
                    "netlist_path": str(Path(root) / "syn" / "net.v"), "log": "", "report_path": ""}
        return {"success": False, "gate_count": 0, "log": "ERROR: synth failed", "log_path": ""}

    def fake_ppa(project_root, block_name, rtl_path, synth_result, *, require_gate_flag=True):
        _hit("evaluate_ppa_gate")
        return True, [], {"wns_ns": 1.25, "tns_ns": 0.0, "timing_required": True, "cells": 42, "ff": 8,
                          "area_um2": 12.5, "sta_report_path": ""}

    monkeypatch.setattr(pg, "generate_rtl", fake_generate_rtl)
    monkeypatch.setattr(pg, "lint_rtl", fake_lint)
    monkeypatch.setattr(pg, "fix_lint_errors", AsyncMock(return_value=None))
    monkeypatch.setattr(pg, "generate_testbench", fake_generate_tb)
    monkeypatch.setattr(pg, "run_simulation", fake_sim)
    monkeypatch.setattr(pg, "fix_testbench_errors", AsyncMock(return_value=None))
    monkeypatch.setattr(pg, "synthesize_block", fake_synth)
    monkeypatch.setattr(pg, "fix_synth_errors", AsyncMock(return_value=None))
    monkeypatch.setattr(pg, "_evaluate_ppa_gate", fake_ppa)
    monkeypatch.setattr(pg, "_run_gate_sim_gate", lambda *a, **k: (None, "disabled", "test"))
    monkeypatch.setattr(pg, "create_golden_model_wrapper", lambda *a, **k: None)
    monkeypatch.setattr(pg, "_vip_tb_lint", lambda *a, **k: [])
    monkeypatch.setattr(pg, "diagnose_failure", AsyncMock(return_value={"category": "LOGIC_ERROR", "diagnosis": "fake"}))
    return counts


def make_build_lifecycle(root: Path):
    from orchestrator.graph_lifecycle import GraphLifecycle
    from orchestrator.module_build import checkpoint_db_path
    return GraphLifecycle(name="build", checkpoint_db=checkpoint_db_path(root),
                          builder_fn_path="orchestrator.langgraph.pipeline_graph",
                          builder_fn_name="build_block_graph", project_root=str(root))


def complete_build(db, root, module="tiny", *, entry="build_module", seed=None, thread_id=None) -> str:
    """A completed build recorded directly (no graph): the row with its
    inputs, the evidence rows a passing attempt leaves (DV pass, coverage
    closure, synthesis PPA verdict with timing), and the committed pass with
    the produced-output identity. Its completion names the recorded thread,
    but no checkpoint exists for it: the lineage report never calls it the
    intended workflow."""
    from orchestrator.state_store.store import Scoreboard
    inputs = B.module_inputs(db, root, module, seed_path=seed, target_clock_mhz=50.0)
    bid = B.new_build_id(module)
    thread = thread_id or f"build-{bid}"
    B.record_dispatch(db, build_id=bid, module=module, entry=entry, graph="build", thread_id=thread,
                      inputs=inputs, seed=inputs.get("seed"))
    B.mark_started(db, bid)
    sb = Scoreboard(root)
    assert sb.record_dv(block=module, scope="rtl", source="gate", attempt=1, passed=True, build_id=bid, run_id=db.run_id())
    assert sb.record_coverage(block=module, scope="rtl", pct=90.0, attempt=1, source="gate",
                              uncovered={"applicable": True, "floor": 80.0, "passed": True}, build_id=bid)
    assert sb.record_ppa(block=module, attempt=1, source="gate", probe="synth", cells=10, wns_ns=0.5, ppa_ok=True,
                         build_id=bid, stage="synth", tool="yosys+opensta", pdk="sky130A", clock_mhz=50.0,
                         power_mw=None, power_basis="unavailable")
    problems, _rows = B.verify_build_evidence(root, bid, attempt=1, timing_required=True)
    assert problems == [], problems
    tb = Path(root) / "tb" / "cocotb" / f"test_{module}.py"
    if not tb.exists():
        tb.parent.mkdir(parents=True, exist_ok=True)
        tb.write_text("import cocotb\n")
    spec = next((b for b in db.block_specs() if b["name"] == module), {})
    rtl = Path(root) / (spec.get("rtl_target") or f"rtl/{module}.v")
    produced = B.produced_outputs(root, module, inputs.get("target"), tb_path=str(tb), rtl_path=str(rtl))
    assert not produced["missing"], produced
    db.set_result(module, "dv_best", {"sim_passed": True, "build_id": bid})
    db.publish_build_result(module, {"done": True, "sim_passed": True, "synth_success": True, "attempt": 1},
                            build_id=bid, build_result={"attempt": 1, "produced": produced, "timing_required": True,
                                                        "thread_id": thread, "checkpoint_ns": ""})
    return bid


def run_block_done(state: dict, *, thread_id: str) -> dict:
    """``block_done_node`` executed as a node of a compiled LangGraph on a
    checkpointed thread (the node reads its graph identity from the running
    task; outside a graph it refuses to publish)."""
    import asyncio as _asyncio

    from langgraph.checkpoint.memory import MemorySaver
    from langgraph.graph import END, START, StateGraph

    from orchestrator.langgraph import pipeline_graph as pg
    g = StateGraph(pg.BlockState)
    g.add_node("block_done", pg.block_done_node)
    g.add_edge(START, "block_done")
    g.add_edge("block_done", END)
    app = g.compile(checkpointer=MemorySaver())
    return _asyncio.run(app.ainvoke(state, {"configurable": {"thread_id": thread_id}}))


def events(root: Path) -> list[dict]:
    p = Path(root) / ".coresmith" / "pipeline_events.jsonl"
    if not p.exists():
        return []
    return [json.loads(ln) for ln in p.read_text().splitlines() if ln.strip()]


def snapshot_tree(root: Path, rel: str) -> dict[str, str]:
    base = Path(root) / rel
    return {str(p.relative_to(root)): B.file_sha256(p) for p in sorted(base.rglob("*")) if p.is_file()} if base.exists() else {}


__all__ = ["MODULES", "EDGE", "RTL", "SPEC", "ready_project", "fake_graph_helpers", "make_build_lifecycle",
           "write_env", "record_model_build", "add_primitive", "shared_stages_done", "complete_build",
           "run_block_done", "events", "snapshot_tree", "os", "ACCEPTANCE_TB", "add_module_targets"]
