# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Tests for the post-synthesis GATE-LEVEL SIMULATION gate (harness.gate_sim).

The gate replays the verified RTL's own port vectors through the SYNTHESIZED
NETLIST and fails closed on divergence. These tests pin (a) both branches of the
``CORESMITH_GATE_SIM`` env gate, (b) the netlist/VCD plumbing that has to be
exactly right for the comparison to mean anything, and (c) every fail-closed
path -- blank verdict, zero cycles, zero compared bits, vacuous stimulus,
unmodelled macro, netlist that will not elaborate.

The live Verilator build is exercised at the LOGIC level here via an injected
runner: the mechanism and the fail semantics are what these tests pin, not the
toolchain (which is not present on every host).
"""
from __future__ import annotations

import json

import pytest

from orchestrator.harness import gate_sim as gs

_NETLIST = """/* Generated by Yosys */
module blk(clk, rst_n, en, q, valid);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [7:0] q;
  wire [7:0] q;
  output valid;
  wire valid;
  sky130_fd_sc_hd__dfxtp_1 _00_ (.CLK(clk), .D(en), .Q(valid));
endmodule
"""

_BLOCK = {"name": "blk"}


# --------------------------------------------------------------------------- #
# env gate -- BOTH branches
# --------------------------------------------------------------------------- #
def test_gate_default_on(monkeypatch):
    monkeypatch.delenv(gs.GATE_SIM_ENV, raising=False)
    assert gs.gate_sim_enabled() is True


def test_gate_force_off(monkeypatch):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "0")
    assert gs.gate_sim_enabled() is False


@pytest.mark.parametrize("raw", ["false", "no", "off", "OFF"])
def test_gate_off_spellings(monkeypatch, raw):
    monkeypatch.setenv(gs.GATE_SIM_ENV, raw)
    assert gs.gate_sim_enabled() is False


@pytest.mark.parametrize("raw", ["1", "true", "yes", "on"])
def test_gate_on_spellings(monkeypatch, raw):
    monkeypatch.setenv(gs.GATE_SIM_ENV, raw)
    assert gs.gate_sim_enabled() is True


def test_disabled_gate_short_circuits_and_says_so(monkeypatch, tmp_path):
    """OFF must return a DISABLED status whose reason names the risk -- never a
    silent pass that a downstream reader mistakes for a real verdict."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "0")
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "nope.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_DISABLED
    assert res.ran is False
    assert res.blocking is False
    assert "never simulated" in res.reason or "NEVER" in res.reason


def test_enabled_gate_actually_evaluates_the_netlist(monkeypatch, tmp_path):
    """ON must reach the netlist check and report on it; OFF short-circuits
    before looking at anything (the observable difference between branches)."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "nope.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert "NO NETLIST" in res.reason


def test_strict_gate_both_branches(monkeypatch):
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    assert gs.gate_sim_strict() is False
    monkeypatch.setenv("CORESMITH_GATE_SIM_STRICT", "1")
    assert gs.gate_sim_strict() is True


def test_max_cycles_and_timeout_env(monkeypatch):
    monkeypatch.delenv("CORESMITH_GATE_SIM_MAX_CYCLES", raising=False)
    assert gs.gate_sim_max_cycles() == 200000
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_CYCLES", "512")
    assert gs.gate_sim_max_cycles() == 512
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_CYCLES", "garbage")
    assert gs.gate_sim_max_cycles() == 200000
    monkeypatch.setenv("CORESMITH_GATE_SIM_TIMEOUT_S", "60")
    assert gs.gate_sim_timeout_s() == 60


def test_macro_model_mode_env(monkeypatch):
    monkeypatch.delenv("CORESMITH_GATE_SIM_MACRO_MODEL", raising=False)
    assert gs.gate_sim_macro_model_mode() == "generated"
    monkeypatch.setenv("CORESMITH_GATE_SIM_MACRO_MODEL", "pdk")
    assert gs.gate_sim_macro_model_mode() == "pdk"


# --------------------------------------------------------------------------- #
# netlist port parsing
# --------------------------------------------------------------------------- #
def test_parse_netlist_ports():
    ports = gs.parse_netlist_ports(_NETLIST, "blk")
    assert [p.name for p in ports] == ["clk", "rst_n", "en", "q", "valid"]
    q = [p for p in ports if p.name == "q"][0]
    assert (q.direction, q.width) == ("output", 8)
    assert [p for p in ports if p.name == "clk"][0].direction == "input"


def test_parse_netlist_ports_missing_top_is_empty():
    assert gs.parse_netlist_ports(_NETLIST, "other_top") == []


def test_pick_clock():
    ports = gs.parse_netlist_ports(_NETLIST, "blk")
    assert gs.pick_clock(ports).name == "clk"
    assert gs.pick_clock([gs.Port("a", "input"), gs.Port("o", "output")]) is None


# --------------------------------------------------------------------------- #
# VCD -> vectors
# --------------------------------------------------------------------------- #
def _write_vcd(path, lines):
    path.write_text(
        "$timescale 1ns $end\n"
        "$scope module blk $end\n"
        "$var wire 1 ! clk $end\n"
        "$var wire 1 # rst_n $end\n"
        "$var wire 1 % en $end\n"
        "$var wire 8 & q [7:0] $end\n"
        "$var wire 1 ( valid $end\n"
        "$upscope $end\n"
        "$enddefinitions $end\n" + "\n".join(lines) + "\n"
    )
    return path


def _ports():
    return gs.parse_netlist_ports(_NETLIST, "blk")


def test_extract_vectors_samples_pre_edge_state(tmp_path):
    """The snapshot must be the state BEFORE the edge, even when the VCD lists
    the outputs the edge produced in the SAME timestamp block as the clock."""
    vcd = _write_vcd(tmp_path / "d.vcd", [
        "#0", "0!", "0#", "0%", "b0 &", "0(",
        "#5", "1!",                      # posedge 1: pre-edge q=0
        "#10", "0!",
        "#15", "1%",                     # en rises between edges
        "#20", "1!", "b1 &", "1(",       # posedge 2: q/valid change WITH the clk
        "#25", "0!",
        "#30", "1!", "b10 &",            # posedge 3
    ])
    vec = gs.extract_vectors(vcd, _ports(), "clk", 1000)
    assert vec.cycles == 3
    assert vec.inputs == ["rst_n", "en"]
    assert vec.outputs == ["q", "valid"]
    # cycle 1 pre-edge: en=0, q=0
    assert vec.rows[0] == (["0", "0"], ["00000000", "0"])
    # cycle 2 pre-edge: en=1 (changed at #15), q STILL 0 -- the #20 change is
    # the RESULT of this edge and belongs to the next sample.
    assert vec.rows[1] == (["0", "1"], ["00000000", "0"])
    # cycle 3 pre-edge: q=1 from the previous edge.
    assert vec.rows[2] == (["0", "1"], ["00000001", "1"])
    assert vec.output_activity == 2


def test_extract_vectors_respects_max_cycles(tmp_path):
    lines = ["#0", "0!", "0#", "0%", "b0 &", "0("]
    t = 5
    for _ in range(20):
        lines += [f"#{t}", "1!", f"#{t + 5}", "0!"]
        t += 10
    vcd = _write_vcd(tmp_path / "d.vcd", lines)
    assert gs.extract_vectors(vcd, _ports(), "clk", 4).cycles == 4


def test_extract_vectors_missing_vcd_is_empty(tmp_path):
    assert gs.extract_vectors(tmp_path / "absent.vcd", _ports(), "clk", 10).cycles == 0


def test_write_vector_file_roundtrip(tmp_path):
    vcd = _write_vcd(tmp_path / "d.vcd", [
        "#0", "0!", "0#", "0%", "b0 &", "0(", "#5", "1!", "#10", "0!", "#15", "1!",
    ])
    vec = gs.extract_vectors(vcd, _ports(), "clk", 100)
    out = tmp_path / "v.txt"
    gs.write_vector_file(vec, out, "blk", "clk")
    text = out.read_text()
    assert "# cycles 2" in text
    assert "# in rst_n:1 en:1" in text
    assert "# out q:8 valid:1" in text
    assert text.strip().splitlines()[-1] == "0 0 | 00000000 0"


# --------------------------------------------------------------------------- #
# generated collateral
# --------------------------------------------------------------------------- #
def _code_only(src: str) -> str:
    return "\n".join(ln for ln in src.splitlines() if not ln.lstrip().startswith("//"))


def test_udp_shim_covers_every_referenced_primitive():
    src = gs.udp_shim_source(("sky130_fd_sc_hd",))
    for udp in gs._SHIM_UDPS:
        assert f"module {udp} " in src or f"module {udp} (" in src
    # never re-declare the UDPs as `primitive` (Verilator cannot compile those)
    code = _code_only(src)
    assert "primitive" not in code
    assert "table" not in code


def test_udp_shim_emits_every_requested_family():
    src = gs.udp_shim_source(("sky130_fd_sc_hd", "sky130_fd_sc_hvl"))
    assert "sky130_fd_sc_hd__udp_dff$P " in src
    assert "sky130_fd_sc_hvl__udp_dff$P " in src


def test_cell_model_files_selects_only_referenced_libraries(tmp_path):
    root = tmp_path / "pdk"
    for lib in ("sky130_fd_sc_hd", "sky130_fd_sc_hvl"):
        d = root / "sky130A" / "libs.ref" / lib / "verilog"
        d.mkdir(parents=True)
        (d / f"{lib}.v").write_text("// models\n")
    files, prefixes = gs.cell_model_files(root, _NETLIST)
    assert prefixes == ("sky130_fd_sc_hd",)
    assert len(files) == 1


def test_cell_model_files_absent_pdk(tmp_path):
    assert gs.cell_model_files(tmp_path / "nothing", _NETLIST) == ([], ())


def test_macro_model_source_1rw1r_geometry():
    src = gs.macro_model_source("m8x1024", "1rw1r", 8, 1024, 8)
    assert "module m8x1024" in src
    assert "input  wire [9:0] addr0;" in src
    assert "output reg  [7:0] dout0;" in src
    assert "reg [7:0] mem [0:1023];" in src
    assert "always @(posedge clk1)" in src
    # a cycle-accurate model must not carry the PDK model's delays or tracing
    code = _code_only(src)
    assert "#(" not in code and "$display" not in code


def test_macro_model_source_write_mask_slices():
    src = gs.macro_model_source("m32x256", "1rw1r", 32, 256, 8)
    assert "if (wmask0[3]) mem[addr0][31:24]" in src


def test_macro_model_source_unknown_ports_is_empty():
    assert gs.macro_model_source("weird", "3q", 8, 16, 8) == ""


def test_render_driver_cpp_is_design_agnostic():
    ports = _ports()
    cpp = gs.render_driver_cpp("blk", ports, "clk")
    assert "Vblk.h" in cpp
    assert "dut->en = parse_scalar" in cpp
    assert 'record("q", cycle' in cpp
    # the clock is generated, never driven from or compared against the vectors
    assert "dut->clk = parse_scalar" not in cpp
    assert 'record("clk"' not in cpp
    # the verdict must always carry the two anti-blank counters
    assert "cycles_compared" in cpp and "output_bits_compared" in cpp


def test_render_driver_cpp_handles_wide_ports():
    ports = [gs.Port("clk", "input"), gs.Port("wide_i", "input", 96, 95, 0),
             gs.Port("wide_o", "output", 130, 129, 0)]
    cpp = gs.render_driver_cpp("blk", ports, "clk")
    assert "parse_wide(in_tok[0], w, 3)" in cpp
    assert "uint32_t w[5]; parse_wide" in cpp


# --------------------------------------------------------------------------- #
# fail-closed semantics
# --------------------------------------------------------------------------- #
def _stub_env(monkeypatch, tmp_path, *, netlist=_NETLIST):
    """Make check_gate_sim reach the reference-run stage on any host."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    pdk = tmp_path / "pdk" / "sky130A" / "libs.ref" / "sky130_fd_sc_hd" / "verilog"
    pdk.mkdir(parents=True)
    (pdk / "sky130_fd_sc_hd.v").write_text("// models\n")
    monkeypatch.setattr(gs, "macro_model_files", lambda *_a, **_k: ([], []))
    net = tmp_path / "net.v"
    net.write_text(netlist)
    return net, tmp_path / "pdk"


def test_missing_netlist_is_not_run_and_strict_makes_it_a_failure(monkeypatch, tmp_path):
    """No netlist on disk = nothing for THIS gate to judge (that is the synth
    gate's verdict), so it is a loud ``not_run`` -- and a hard FAIL under
    STRICT, where the caller demanded the gate really run."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "gone.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN and res.blocking is False
    assert "NO NETLIST" in res.reason
    monkeypatch.setenv("CORESMITH_GATE_SIM_STRICT", "1")
    res2 = gs.check_gate_sim(_BLOCK, str(tmp_path / "gone.v"), "r.v", "tb.py")
    assert res2.status == gs.STATUS_FAIL and res2.blocking


def test_empty_netlist_fails_closed(monkeypatch, tmp_path):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    net = tmp_path / "n.v"
    net.write_text("   \n")
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_FAIL


def test_wrong_top_in_netlist_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    res = gs.check_gate_sim({"name": "other"}, str(net), "r.v", "tb.py",
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "not found" in res.reason


def test_toolchain_check_precedes_the_netlist_verdict(monkeypatch, tmp_path):
    """The gate must only render a VERDICT where it could actually have run.
    With no simulator/PDK, even a missing netlist is ``not_run`` -- otherwise a
    PDK-free frontend host would fail every block on a gate it cannot execute
    (and, in the pipeline, spin the retry loop)."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    monkeypatch.setattr(gs.shutil, "which", lambda _n: None)
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "gone.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.blocking is False

    # ...but a host WITH the toolchain and PDK does judge a missing netlist.
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    pdkdir = tmp_path / "pdk" / "sky130A" / "libs.ref" / "sky130_fd_sc_hd" / "verilog"
    pdkdir.mkdir(parents=True)
    (pdkdir / "sky130_fd_sc_hd.v").write_text("// models\n")
    net = tmp_path / "empty.v"
    net.write_text("   \n")
    res2 = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                             pdk_root=tmp_path / "pdk",
                             work_root=tmp_path / "work")
    assert res2.status == gs.STATUS_FAIL and res2.blocking


def test_absent_toolchain_is_not_run_not_pass(monkeypatch, tmp_path):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    monkeypatch.setattr(gs.shutil, "which", lambda _n: None)
    net = tmp_path / "n.v"
    net.write_text(_NETLIST)
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.ran is False
    assert res.blocking is False


def test_absent_toolchain_under_strict_is_a_failure(monkeypatch, tmp_path):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setenv("CORESMITH_GATE_SIM_STRICT", "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: None)
    net = tmp_path / "n.v"
    net.write_text(_NETLIST)
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_FAIL and res.blocking


def test_unmodellable_macro_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(gs, "macro_model_files", lambda *_a, **_k: ([], ["odd_macro"]))
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py", pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "odd_macro" in res.reason


def test_failed_reference_run_is_not_run(monkeypatch, tmp_path):
    """A reference that did not pass gives nothing trustworthy to compare
    against; that is an RTL/DV verdict, not a netlist verdict."""
    net, pdk = _stub_env(monkeypatch, tmp_path)

    def runner(*_a, **_k):
        return {"passed": False, "log": "boom"}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.blocking is False


def test_reference_without_waveform_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)

    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(tmp_path / "absent.vcd")}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "no waveform" in res.reason


def test_zero_recorded_cycles_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    vcd = _write_vcd(tmp_path / "d.vcd", ["#0", "0!", "0#", "0%", "b0 &", "0("])

    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(vcd)}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "no clock cycles" in res.reason


def test_vacuous_stimulus_fails_closed(monkeypatch, tmp_path):
    """Outputs that never move across the whole run make the comparison
    meaningless -- that must not be scored as a gate-sim pass."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    lines = ["#0", "0!", "0#", "0%", "b0 &", "0("]
    t = 5
    for _ in range(6):
        lines += [f"#{t}", "1!", f"#{t + 5}", "0!"]
        t += 10
    vcd = _write_vcd(tmp_path / "d.vcd", lines)

    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(vcd)}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "vacuous" in res.reason


def _good_ref(tmp_path):
    lines = ["#0", "0!", "0#", "0%", "b0 &", "0("]
    t = 5
    for i in range(6):
        lines += [f"#{t}", "1!", f"b{i % 2} &"]
        lines += [f"#{t + 5}", "0!"]
        t += 10
    return _write_vcd(tmp_path / "d.vcd", lines)


def _runner_for(vcd):
    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(vcd)}
    return runner


def test_blank_verdict_fails_closed(monkeypatch, tmp_path):
    """The single most important property: a gate sim that produced no verdict
    must NEVER read as a pass."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": False, "stage": "verdict",
                      "error": "gate simulation produced no verdict file"},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "no verdict" in res.reason


def test_netlist_that_will_not_elaborate_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": False, "stage": "verilate",
                      "error": "the gate netlist did not elaborate/build"},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "elaborate" in res.reason


def test_zero_cycles_compared_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 0,
                      "output_bits_compared": 0, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "0 cycles" in res.reason


def test_zero_bits_compared_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 0, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "0 output bits" in res.reason


def test_divergence_fails_closed_with_first_mismatch(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 4,
                      "output_bits_compared": 36, "diverged": True,
                      "first_divergence": {"cycle": 3, "port": "q",
                                           "expected": "00000001",
                                           "actual": "0"}},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL and res.blocking
    assert res.first_divergence["port"] == "q"
    report = res.as_prev_error("blk")
    assert "FIRST DIVERGENCE at cycle 3" in report
    assert "`ifdef" in report          # names the split-implementation cause


def test_matching_netlist_passes(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 54, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_PASS
    assert res.ran is True and res.ok is True and res.blocking is False
    assert res.cycles_compared == 6


def test_reference_run_is_isolated_and_seed_pinned(monkeypatch, tmp_path):
    """The reference must build in its OWN dir (never clobbering the block's DV
    build) under a PINNED seed, with the shallow port-only trace."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    seen = {}

    def runner(block, rtl_path, tb_path, attempt=1, extra_defines=None,
               sim_subdir=None, extra_args=None):
        import os as _os
        seen.update({"subdir": sim_subdir, "args": extra_args,
                     "defines": extra_defines,
                     "seed": _os.environ.get("CORESMITH_DV_SEED_PIN")})
        return {"passed": True, "vcd_path": str(_good_ref(tmp_path))}

    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 54, "diverged": False},
    )
    monkeypatch.delenv("CORESMITH_DV_SEED_PIN", raising=False)
    gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py", sim_runner=runner,
                      pdk_root=pdk, work_root=tmp_path / "work")
    assert seen["subdir"] == "blk__gatesim_ref"
    assert seen["args"] == ["--trace-depth 1"]
    assert seen["defines"] is None
    assert seen["seed"]
    # ...and the pin is restored afterwards
    import os as _os
    assert _os.environ.get("CORESMITH_DV_SEED_PIN") is None


def test_result_serializes_for_the_report(monkeypatch, tmp_path):
    res = gs.GateSimResult(ran=True, ok=False, status=gs.STATUS_FAIL,
                           reason="diverged", cycles_compared=3)
    blob = json.loads(json.dumps(res.as_dict()))
    assert blob["status"] == gs.STATUS_FAIL
    assert blob["cycles_compared"] == 3
