# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Tests for the post-synthesis GATE-LEVEL SIMULATION gate (harness.gate_sim).

The gate replays the verified RTL's own port vectors through the SYNTHESIZED
NETLIST and fails closed on divergence. These tests pin (a) both branches of the
``CORESMITH_GATE_SIM`` env gate and of the scope guard, (b) the netlist/VCD
plumbing that has to be exactly right for the comparison to mean anything,
(c) every fail-closed path -- blank verdict, zero cycles, zero compared bits,
vacuous stimulus, unmodelled macro, netlist that will not elaborate, (d) that a
generated hard-macro stand-in matches the REAL macro's declared interface, and
(e) that a power-only tri-state boundary is judged while a signal one is not.

The live Verilator build is exercised at the LOGIC level here via an injected
runner: the mechanism and the fail semantics are what these tests pin, not the
toolchain (which is not present on every host).
"""
from __future__ import annotations

import json

import pytest

from orchestrator.harness import gate_sim as gs

_NETLIST = """/* Generated by Yosys */
module blk(clk, rst_n, en, q, valid);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  output [7:0] q;
  wire [7:0] q;
  output valid;
  wire valid;
  sky130_fd_sc_hd__dfxtp_1 _00_ (.CLK(clk), .D(en), .Q(valid));
endmodule
"""

# The same netlist with a Caravel-style POWER-ONLY bidirectional boundary.
_NETLIST_RAILS = _NETLIST.replace(
    "module blk(clk, rst_n, en, q, valid);",
    "module blk(clk, rst_n, en, q, valid, vccd1, vssd1);",
).replace(
    "  sky130_fd_sc_hd__dfxtp_1",
    "  inout vccd1;\n  wire vccd1;\n  inout vssd1;\n  wire vssd1;\n"
    "  sky130_fd_sc_hd__dfxtp_1",
)

# The same netlist with a real bidirectional SIGNAL on the boundary.
# The tristate port is genuinely DRIVEN (a conditional-Z assign): the veto is
# for bidirectional SIGNALS. A declared-but-unreferenced inout, or one tied to
# constant Z, is INERT -- a mandated-but-unused pad bus like Caravel analog_io --
# and deliberately does not veto (test_a_z_tied_unused_inout_is_inert_not_a_veto).
_NETLIST_TRISTATE = _NETLIST.replace(
    "module blk(clk, rst_n, en, q, valid);",
    "module blk(clk, rst_n, en, q, valid, sda);",
).replace(
    "  sky130_fd_sc_hd__dfxtp_1",
    "  inout sda;\n  wire sda;\n"
    "  assign sda = en ? 1'b0 : 1'bz;\n  sky130_fd_sc_hd__dfxtp_1",
)

# The subject under test declares itself the chip top. The gate's DEFAULT SCOPE
# is chip_top -- a per-block netlist is an intermediate whose stimulus is that
# block's own testbench, not the artifact that becomes silicon -- so a subject
# that is not marked would be `not_run` before any verdict logic ran, and these
# tests are about the verdict logic. The leaf-block behaviour has its own test
# (``test_leaf_block_is_not_run_under_the_default_scope``); it is deliberately
# NOT worked around by weakening the guard.
_BLOCK = {"name": "blk", "is_chip_top": True}


# --------------------------------------------------------------------------- #
# env gate -- BOTH branches
# --------------------------------------------------------------------------- #
def test_gate_default_on(monkeypatch):
    monkeypatch.delenv(gs.GATE_SIM_ENV, raising=False)
    assert gs.gate_sim_enabled() is True


def test_gate_force_off(monkeypatch):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "0")
    assert gs.gate_sim_enabled() is False


@pytest.mark.parametrize("raw", ["false", "no", "off", "OFF"])
def test_gate_off_spellings(monkeypatch, raw):
    monkeypatch.setenv(gs.GATE_SIM_ENV, raw)
    assert gs.gate_sim_enabled() is False


@pytest.mark.parametrize("raw", ["1", "true", "yes", "on"])
def test_gate_on_spellings(monkeypatch, raw):
    monkeypatch.setenv(gs.GATE_SIM_ENV, raw)
    assert gs.gate_sim_enabled() is True


def test_disabled_gate_short_circuits_and_says_so(monkeypatch, tmp_path):
    """OFF must return a DISABLED status whose reason names the risk -- never a
    silent pass that a downstream reader mistakes for a real verdict."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "0")
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "nope.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_DISABLED
    assert res.ran is False
    assert res.blocking is False
    assert "never simulated" in res.reason or "NEVER" in res.reason


def test_enabled_gate_actually_evaluates_the_netlist(monkeypatch, tmp_path):
    """ON must reach the netlist check and report on it; OFF short-circuits
    before looking at anything (the observable difference between branches)."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "nope.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert "NO NETLIST" in res.reason


# --------------------------------------------------------------------------- #
# scope guard -- the gate judges chip_top by default
# --------------------------------------------------------------------------- #
def test_scope_defaults_to_chip_top(monkeypatch):
    monkeypatch.delenv(gs.GATE_SIM_SCOPE_ENV, raising=False)
    assert gs.gate_sim_scope() == "chip_top"
    monkeypatch.setenv(gs.GATE_SIM_SCOPE_ENV, "block")
    assert gs.gate_sim_scope() == "block"
    monkeypatch.setenv(gs.GATE_SIM_SCOPE_ENV, "any")
    assert gs.gate_sim_scope() == "any"
    monkeypatch.setenv(gs.GATE_SIM_SCOPE_ENV, "nonsense")
    assert gs.gate_sim_scope() == "chip_top", "an unknown scope must not widen it"


@pytest.mark.parametrize("block", [
    {"name": "blk", "is_chip_top": True},
    {"name": "blk", "scope": "chip_top"},
    {"name": "chip_top"},
    {"name": "integration"},
    {"name": "my_design_chip_top"},
])
def test_block_is_chip_top_recognises_the_top(block):
    assert gs.block_is_chip_top(block) is True


@pytest.mark.parametrize("block", [{"name": "blk"}, {"name": "fifo"}, {}])
def test_block_is_chip_top_rejects_a_leaf(block):
    assert gs.block_is_chip_top(block) is False


def test_leaf_block_is_not_run_under_the_default_scope(monkeypatch, tmp_path):
    """NEW BEHAVIOUR: with the default scope the gate judges the integrated
    chip_top netlist only. A LEAF block is ``not_run`` -- never a pass and never
    a failure -- and the reason has to say why and how to opt in, because a
    silent skip is indistinguishable from a check that passed."""
    monkeypatch.delenv(gs.GATE_SIM_ENV, raising=False)          # default ON
    monkeypatch.delenv(gs.GATE_SIM_SCOPE_ENV, raising=False)    # default chip_top
    net = tmp_path / "n.v"
    net.write_text(_NETLIST)
    res = gs.check_gate_sim({"name": "fifo"}, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.ran is False and res.blocking is False
    assert "fifo" in res.reason and "chip_top" in res.reason
    assert gs.GATE_SIM_SCOPE_ENV in res.reason


def test_scope_block_admits_a_leaf_again(monkeypatch, tmp_path):
    """The per-block replay is still available -- it is how a synthesis-side
    stub scoring 143/144 line coverage was caught."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setenv(gs.GATE_SIM_SCOPE_ENV, "block")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    res = gs.check_gate_sim({"name": "fifo"}, str(tmp_path / "gone.v"),
                            "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert "NO NETLIST" in res.reason, "reached the netlist check, not the guard"


def test_disabled_outranks_out_of_scope(monkeypatch, tmp_path):
    """A reader of a leaf block's report must be told the gate is OFF, not that
    the subject was out of scope -- nothing would have run either way."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "0")
    monkeypatch.delenv(gs.GATE_SIM_SCOPE_ENV, raising=False)
    res = gs.check_gate_sim({"name": "fifo"}, str(tmp_path / "n.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_DISABLED


def test_strict_gate_both_branches(monkeypatch):
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    assert gs.gate_sim_strict() is False
    monkeypatch.setenv("CORESMITH_GATE_SIM_STRICT", "1")
    assert gs.gate_sim_strict() is True


def test_max_cycles_and_timeout_env(monkeypatch):
    monkeypatch.delenv("CORESMITH_GATE_SIM_MAX_CYCLES", raising=False)
    assert gs.gate_sim_max_cycles() == 200000
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_CYCLES", "512")
    assert gs.gate_sim_max_cycles() == 512
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_CYCLES", "garbage")
    assert gs.gate_sim_max_cycles() == 200000
    monkeypatch.setenv("CORESMITH_GATE_SIM_TIMEOUT_S", "60")
    assert gs.gate_sim_timeout_s() == 60


def test_macro_model_mode_env(monkeypatch):
    monkeypatch.delenv("CORESMITH_GATE_SIM_MACRO_MODEL", raising=False)
    assert gs.gate_sim_macro_model_mode() == "generated"
    monkeypatch.setenv("CORESMITH_GATE_SIM_MACRO_MODEL", "pdk")
    assert gs.gate_sim_macro_model_mode() == "pdk"


def test_debug_env_both_branches(monkeypatch):
    monkeypatch.delenv(gs.GATE_SIM_DEBUG_ENV, raising=False)
    assert gs.gate_sim_debug() is False
    monkeypatch.setenv(gs.GATE_SIM_DEBUG_ENV, "1")
    assert gs.gate_sim_debug() is True
    monkeypatch.delenv("CORESMITH_GATE_SIM_MAX_DIVERGENCES", raising=False)
    assert gs.gate_sim_max_divergences() == 32
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_DIVERGENCES", "4")
    assert gs.gate_sim_max_divergences() == 4
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_DIVERGENCES", "garbage")
    assert gs.gate_sim_max_divergences() == 32


# --------------------------------------------------------------------------- #
# netlist port parsing
# --------------------------------------------------------------------------- #
def test_parse_netlist_ports():
    ports = gs.parse_netlist_ports(_NETLIST, "blk")
    assert [p.name for p in ports] == ["clk", "rst_n", "en", "q", "valid"]
    q = [p for p in ports if p.name == "q"][0]
    assert (q.direction, q.width) == ("output", 8)
    assert [p for p in ports if p.name == "clk"][0].direction == "input"


def test_parse_netlist_ports_missing_top_is_empty():
    assert gs.parse_netlist_ports(_NETLIST, "other_top") == []


def test_pick_clock():
    ports = gs.parse_netlist_ports(_NETLIST, "blk")
    assert gs.pick_clock(ports).name == "clk"
    assert gs.pick_clock([gs.Port("a", "input"), gs.Port("o", "output")]) is None


# --------------------------------------------------------------------------- #
# VCD -> vectors
# --------------------------------------------------------------------------- #
def _write_vcd(path, lines):
    path.write_text(
        "$timescale 1ns $end\n"
        "$scope module blk $end\n"
        "$var wire 1 ! clk $end\n"
        "$var wire 1 # rst_n $end\n"
        "$var wire 1 % en $end\n"
        "$var wire 8 & q [7:0] $end\n"
        "$var wire 1 ( valid $end\n"
        "$upscope $end\n"
        "$enddefinitions $end\n" + "\n".join(lines) + "\n"
    )
    return path


def _ports():
    return gs.parse_netlist_ports(_NETLIST, "blk")


def test_extract_vectors_samples_pre_edge_state(tmp_path):
    """The snapshot must be the state BEFORE the edge, even when the VCD lists
    the outputs the edge produced in the SAME timestamp block as the clock."""
    vcd = _write_vcd(tmp_path / "d.vcd", [
        "#0", "0!", "0#", "0%", "b0 &", "0(",
        "#5", "1!",                      # posedge 1: pre-edge q=0
        "#10", "0!",
        "#15", "1%",                     # en rises between edges
        "#20", "1!", "b1 &", "1(",       # posedge 2: q/valid change WITH the clk
        "#25", "0!",
        "#30", "1!", "b10 &",            # posedge 3
    ])
    vec = gs.extract_vectors(vcd, _ports(), "clk", 1000)
    assert vec.cycles == 3
    assert vec.inputs == ["rst_n", "en"]
    assert vec.outputs == ["q", "valid"]
    # cycle 1 pre-edge: en=0, q=0
    assert vec.rows[0] == (["0", "0"], ["00000000", "0"])
    # cycle 2 pre-edge: en=1 (changed at #15), q STILL 0 -- the #20 change is
    # the RESULT of this edge and belongs to the next sample.
    assert vec.rows[1] == (["0", "1"], ["00000000", "0"])
    # cycle 3 pre-edge: q=1 from the previous edge.
    assert vec.rows[2] == (["0", "1"], ["00000001", "1"])
    assert vec.output_activity == 2


def test_extract_vectors_respects_max_cycles(tmp_path):
    lines = ["#0", "0!", "0#", "0%", "b0 &", "0("]
    t = 5
    for _ in range(20):
        lines += [f"#{t}", "1!", f"#{t + 5}", "0!"]
        t += 10
    vcd = _write_vcd(tmp_path / "d.vcd", lines)
    assert gs.extract_vectors(vcd, _ports(), "clk", 4).cycles == 4


def test_extract_vectors_missing_vcd_is_empty(tmp_path):
    assert gs.extract_vectors(tmp_path / "absent.vcd", _ports(), "clk", 10).cycles == 0


def test_write_vector_file_roundtrip(tmp_path):
    vcd = _write_vcd(tmp_path / "d.vcd", [
        "#0", "0!", "0#", "0%", "b0 &", "0(", "#5", "1!", "#10", "0!", "#15", "1!",
    ])
    vec = gs.extract_vectors(vcd, _ports(), "clk", 100)
    out = tmp_path / "v.txt"
    gs.write_vector_file(vec, out, "blk", "clk")
    text = out.read_text()
    assert "# cycles 2" in text
    assert "# in rst_n:1 en:1" in text
    assert "# out q:8 valid:1" in text
    assert text.strip().splitlines()[-1] == "0 0 | 00000000 0"


# --------------------------------------------------------------------------- #
# generated collateral
# --------------------------------------------------------------------------- #
def _code_only(src: str) -> str:
    return "\n".join(ln for ln in src.splitlines() if not ln.lstrip().startswith("//"))


def test_udp_shim_covers_every_referenced_primitive():
    src = gs.udp_shim_source(("sky130_fd_sc_hd",))
    for udp in gs._SHIM_UDPS:
        assert f"module {udp} " in src or f"module {udp} (" in src
    # never re-declare the UDPs as `primitive` (Verilator cannot compile those)
    code = _code_only(src)
    assert "primitive" not in code
    assert "table" not in code


def test_udp_shim_emits_every_requested_family():
    src = gs.udp_shim_source(("sky130_fd_sc_hd", "sky130_fd_sc_hvl"))
    assert "sky130_fd_sc_hd__udp_dff$P " in src
    assert "sky130_fd_sc_hvl__udp_dff$P " in src


def test_cell_model_files_selects_only_referenced_libraries(tmp_path):
    root = tmp_path / "pdk"
    for lib in ("sky130_fd_sc_hd", "sky130_fd_sc_hvl"):
        d = root / "sky130A" / "libs.ref" / lib / "verilog"
        d.mkdir(parents=True)
        (d / f"{lib}.v").write_text("// models\n")
    files, prefixes = gs.cell_model_files(root, _NETLIST)
    assert prefixes == ("sky130_fd_sc_hd",)
    assert len(files) == 1


def test_cell_model_files_absent_pdk(tmp_path):
    assert gs.cell_model_files(tmp_path / "nothing", _NETLIST) == ([], ())


# --------------------------------------------------------------------------- #
# hard-macro stand-in: the interface is READ from the real macro, not guessed
# --------------------------------------------------------------------------- #
def _openram_model(tmp_path, name, *, data_bits, addr_bits, nmask=0, gran=8,
                   extra_port=""):
    """Write a structurally faithful OpenRAM sky130 1rw1r behavioural model.

    Reproduces exactly the shape the PDK ships -- non-ANSI header, geometry
    behind ``parameter``s, supplies behind ```ifdef USE_POWER_PINS``, and the
    ``merge_write0`` function whose ``if (write_mask[i])`` arms are the ground
    truth for which data bits each mask bit covers. ``nmask=0`` models the
    ``word_size == write_size`` case, where OpenRAM omits ``wmask0`` ENTIRELY.
    """
    wm_hdr = "wmask0," if nmask else ""
    wm_decl = ("  input [NUM_WMASKS-1:0]   wmask0; // write mask\n"
               if nmask else "")
    wm_arg = "    input [NUM_WMASKS-1:0] write_mask;\n" if nmask else ""
    if nmask:
        arms = "".join(
            f"      if (write_mask[{i}])\n"
            f"        merge_write0[{min((i + 1) * gran - 1, data_bits - 1)}:"
            f"{i * gran}] = new_word[{min((i + 1) * gran - 1, data_bits - 1)}:"
            f"{i * gran}];\n"
            for i in range(nmask))
    else:
        arms = (f"      merge_write0[{data_bits - 1}:0] = "
                f"new_word[{data_bits - 1}:0];\n")
    src = f"""`timescale 1ns/1ps

// OpenRAM SRAM model
// Words: {1 << addr_bits}
// Word size: {data_bits}

module {name}(
`ifdef USE_POWER_PINS
    vccd1,
    vssd1,
`endif
// Port 0: RW
    clk0,csb0,web0,{wm_hdr}addr0,din0,dout0,
// Port 1: R
    clk1,csb1,addr1,dout1{"," + extra_port if extra_port else ""}
  );

  parameter NUM_WMASKS = {nmask} ;
  parameter DATA_WIDTH = {data_bits} ;
  parameter ADDR_WIDTH = {addr_bits} ;
  parameter RAM_DEPTH = 1 << ADDR_WIDTH;
  parameter T_HOLD = 1 ;

`ifdef USE_POWER_PINS
    inout vccd1;
    inout vssd1;
`endif
  input  clk0; // clock
  input   csb0; // active low chip select
  input  web0; // active low write control
{wm_decl}  input [ADDR_WIDTH-1:0]  addr0;
  input [DATA_WIDTH-1:0]  din0;
  output [DATA_WIDTH-1:0] dout0;
  input  clk1; // clock
  input   csb1; // active low chip select
  input [ADDR_WIDTH-1:0]  addr1;
  output [DATA_WIDTH-1:0] dout1;
{"  input  " + extra_port + ";" if extra_port else ""}

  reg [DATA_WIDTH-1:0]    mem [0:RAM_DEPTH-1];

  function [DATA_WIDTH-1:0] merge_write0;
    input [DATA_WIDTH-1:0] old_word;
    input [DATA_WIDTH-1:0] new_word;
{wm_arg}    begin
      merge_write0 = old_word;
{arms}    end
  endfunction
endmodule
"""
    p = tmp_path / f"{name}.v"
    p.write_text(src)
    return p


def test_macro_interface_reads_the_real_declarations(tmp_path):
    p = _openram_model(tmp_path, "m32x256", data_bits=32, addr_bits=8, nmask=4)
    iface = gs.macro_interface("m32x256", p)
    assert iface is not None
    assert iface.order == ["clk0", "csb0", "web0", "wmask0", "addr0", "din0",
                           "dout0", "clk1", "csb1", "addr1", "dout1"]
    assert iface.widths["wmask0"] == 4
    assert iface.widths["addr0"] == 8
    assert iface.widths["din0"] == 32
    # supplies are NOT functional ports; they stay behind the ifdef
    assert iface.power_pins == ["vccd1", "vssd1"]
    assert "vccd1" not in iface.order
    # the merge function is the ground truth for the mask slicing
    assert iface.mask_slices == [(7, 0), (15, 8), (23, 16), (31, 24)]


def test_macro_stand_in_geometry_comes_from_the_declarations(tmp_path):
    p = _openram_model(tmp_path, "m8x1024", data_bits=8, addr_bits=10, nmask=1)
    src = gs.macro_model_source("m8x1024", "1rw1r", 8, 1024, 8,
                                iface=gs.macro_interface("m8x1024", p))
    assert "module m8x1024" in src
    assert "input  wire [9:0] addr0;" in src
    assert "output reg [7:0] dout0;" in src
    # depth is `1 << ADDR_WIDTH`, exactly as the PDK model declares RAM_DEPTH --
    # sizing from the registry's word count would leave an addressable index out
    # of range on a non-power-of-two macro.
    assert "reg [7:0] mem [0:1023];" in src
    assert "always @(posedge clk1)" in src
    # a cycle-accurate model must not carry the PDK model's delays or tracing
    code = _code_only(src)
    assert "#(" not in code and "$display" not in code


def test_macro_stand_in_write_mask_slices(tmp_path):
    p = _openram_model(tmp_path, "m32x256", data_bits=32, addr_bits=8, nmask=4)
    src = gs.macro_model_source("m32x256", "1rw1r", 32, 256, 8,
                                iface=gs.macro_interface("m32x256", p))
    assert "input  wire [3:0] wmask0;" in src
    assert "if (wmask0[3]) mem[addr0][31:24]" in src


def test_macro_stand_in_omits_a_port_the_real_macro_does_not_declare(tmp_path):
    """REGRESSION -- the false FAIL this file exists to prevent.

    ``sram_1rw1r_8_4096_8`` has word_size == write_size == 8, so a single
    whole-word mask bit IS the write enable and OpenRAM omits ``wmask0``
    entirely. The old generator emitted it anyway and gated writes on
    ``wmask0[0]``; the flat netlist correctly left the pin unconnected,
    Verilator tied the floating input LOW, every write was suppressed, every
    read returned zero, and a correctly synthesized netlist "failed" gate sim.
    """
    p = _openram_model(tmp_path, "m8x4096", data_bits=8, addr_bits=12, nmask=0)
    iface = gs.macro_interface("m8x4096", p)
    assert "wmask0" not in iface.order
    src = gs.macro_model_source("m8x4096", "1rw1r", 8, 4096, 8, iface=iface)
    assert "wmask0" not in src, "declared a pin the real macro does not have"
    # ...and the write must not silently vanish with the mask
    assert "if (!web0) begin\n        mem[addr0] <= din0;" in src


def test_macro_stand_in_matches_a_declared_mask_width_exactly(tmp_path):
    """REGRESSION -- the second, opposite instance of the same defect.

    ``sram_1rw1r_9_4096_8`` DOES declare ``wmask0``, as ``[1:0]``
    (NUM_WMASKS == ceil(9/8) == 2). The old generator computed ``9 // 8 == 1``
    and declared ``[0:0]``, so the netlist drove ``2'h3`` into a 1-bit port --
    harmless only because that mask happened to be a constant.
    """
    p = _openram_model(tmp_path, "m9x4096", data_bits=9, addr_bits=12, nmask=2)
    src = gs.macro_model_source("m9x4096", "1rw1r", 9, 4096, 8,
                                iface=gs.macro_interface("m9x4096", p))
    assert "input  wire [1:0] wmask0;" in src
    assert "[0:0] wmask0" not in src
    # the partial final mask group covers exactly one bit, as the real
    # merge_write0 says -- not a rounded-up byte
    assert "if (wmask0[0]) mem[addr0][7:0] <= din0[7:0];" in src
    assert "if (wmask0[1]) mem[addr0][8:8] <= din0[8:8];" in src


def test_macro_stand_in_without_an_interface_is_unresolved():
    """No macro source => no interface => UNRESOLVED, which the caller turns
    into a FAIL. It must never fall back to arithmetic on registry metadata:
    that guess is what shipped two wrong stand-ins."""
    assert gs.macro_model_source("m8x1024", "1rw1r", 8, 1024, 8) == ""
    assert gs.macro_model_source("weird", "3q", 8, 16, 8) == ""


def test_macro_interface_unreadable_source_is_none(tmp_path):
    assert gs.macro_interface("gone", tmp_path / "absent.v") is None
    assert gs.macro_interface("gone", "") is None
    other = tmp_path / "other.v"
    other.write_text("module something_else(input clk);\nendmodule\n")
    assert gs.macro_interface("gone", other) is None


def test_macro_interface_unresolvable_width_is_none(tmp_path):
    """A width we cannot evaluate is UNKNOWN, not 1 and not a default."""
    p = tmp_path / "m.v"
    p.write_text(
        "module m(clk0, csb0, web0, addr0, din0, dout0);\n"
        "  parameter DATA_WIDTH = 8;\n"
        "  input clk0;\n  input csb0;\n  input web0;\n"
        "  input [$clog2(SOMETHING)-1:0] addr0;\n"
        "  input [DATA_WIDTH-1:0] din0;\n"
        "  output [DATA_WIDTH-1:0] dout0;\n"
        "endmodule\n")
    assert gs.macro_interface("m", p) is None


def test_macro_stand_in_refuses_an_unrecognised_pin(tmp_path):
    """A pin this generator does not understand means we do not understand this
    macro. Declaring it as something plausible would be a guess with a verdict
    attached to it."""
    p = _openram_model(tmp_path, "mx", data_bits=8, addr_bits=8, nmask=1,
                       extra_port="rdmode0")
    iface = gs.macro_interface("mx", p)
    assert "rdmode0" in iface.order
    assert gs.macro_model_source("mx", "1rw1r", 8, 256, 8, iface=iface) == ""


def test_macro_stand_in_reads_select_polarity_from_the_macro(tmp_path):
    """OpenRAM SRAMs declare active-LOW ``csb0``; the OpenROM mask-ROM models
    declare active-HIGH ``cs0``. Hard-coding either one inverts every access to
    the other, which reads as plausible garbage rather than an obvious failure.
    A read-only memory also has to load its contents or the stand-in models
    hardware that was never simulated."""
    data = tmp_path / "rom_data.bin"
    data.write_text("00000000\n00000001\n")
    p = tmp_path / "rom_1r_8_4_sky130.v"
    p.write_text(
        "module rom_1r_8_4_sky130(clk0, cs0, addr0, dout0);\n"
        "  parameter DATA_WIDTH = 8 ;\n"
        "  parameter ADDR_WIDTH = 2 ;\n"
        "  input  clk0;\n"
        "  input  cs0; // active high chip select\n"
        "  input [ADDR_WIDTH-1:0] addr0;\n"
        "  output [DATA_WIDTH-1:0] dout0;\n"
        "  reg [DATA_WIDTH-1:0] mem [0:3];\n"
        '  initial $readmemb("rom_data.bin", mem, 0, 3);\n'
        "endmodule\n")
    iface = gs.macro_interface("rom_1r_8_4_sky130", p)
    src = gs.macro_model_source("rom_1r_8_4_sky130", "1r", 8, 4, 0, iface=iface)
    assert "if (cs0) dout0 <= mem[addr0];" in src
    assert "!cs0" not in src, "inverted an active-HIGH select"
    assert f'$readmemb("{data}"' in src

    # ...and a ROM whose contents are not on disk is UNRESOLVED, not a memory
    # full of zeros with a verdict attached.
    data.unlink()
    assert gs.macro_model_source("rom_1r_8_4_sky130", "1r", 8, 4, 0,
                                 iface=iface) == ""


def test_render_driver_cpp_is_design_agnostic():
    ports = _ports()
    cpp = gs.render_driver_cpp("blk", ports, "clk")
    assert "Vblk.h" in cpp
    assert "dut->en = parse_scalar" in cpp
    assert 'record("q", cycle' in cpp
    # the clock is generated, never driven from or compared against the vectors
    assert "dut->clk = parse_scalar" not in cpp
    assert 'record("clk"' not in cpp
    # the verdict must always carry the two anti-blank counters
    assert "cycles_compared" in cpp and "output_bits_compared" in cpp


def test_render_driver_cpp_handles_wide_ports():
    ports = [gs.Port("clk", "input"), gs.Port("wide_i", "input", 96, 95, 0),
             gs.Port("wide_o", "output", 130, 129, 0)]
    cpp = gs.render_driver_cpp("blk", ports, "clk")
    assert "parse_wide(in_tok[0], w, 3)" in cpp
    assert "uint32_t w[5]; parse_wide" in cpp


# --------------------------------------------------------------------------- #
# power/ground boundary vs a real tri-state boundary
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize("name,level", [
    ("vccd1", 1), ("vccd2", 1), ("vdda1", 1), ("vdda2", 1), ("vdd", 1),
    ("vpwr", 1), ("vpb", 1), ("VCCD1", 1),
    ("vssd1", 0), ("vssd2", 0), ("vssa1", 0), ("vssa2", 0), ("vss", 0),
    ("vgnd", 0), ("vnb", 0), ("gnd", 0),
])
def test_power_inout_level_knows_the_rails(name, level):
    assert gs.power_inout_level(name) == level


@pytest.mark.parametrize("name", ["sda", "scl", "io_out", "gpio", "flash_io0",
                                  "dq", "vddish", "my_vccd1", "data"])
def test_power_inout_level_calls_anything_else_a_signal(name):
    """Conservative on purpose: mis-classifying a tri-state SIGNAL as a rail
    would tie it to a constant and then not compare it -- i.e. fabricate a
    pass on the exact port the gate could not judge."""
    assert gs.power_inout_level(name) is None


def test_split_inouts_separates_rails_from_signals():
    ports = [gs.Port("clk", "input"), gs.Port("vccd1", "inout"),
             gs.Port("vssd1", "inout"), gs.Port("sda", "inout"),
             gs.Port("q", "output", 8, 7, 0)]
    rails, _inert, signals = gs.split_inouts(ports)
    assert [p.name for p in rails] == ["vccd1", "vssd1"]
    assert [p.name for p in signals] == ["sda"]


def test_a_wide_inout_is_never_treated_as_a_rail():
    """A supply is one bit. A bus that happens to share a rail's name is not a
    rail we understand, so it stays a signal and still vetoes the gate."""
    rails, inert, signals = gs.split_inouts([gs.Port("vccd1", "inout", 8, 7, 0)])
    assert rails == [] and inert == []
    assert [p.name for p in signals] == ["vccd1"]


def test_a_z_tied_unused_inout_is_inert_not_a_veto():
    """Caravel MANDATES `inout [28:0] analog_io` on every user_project_wrapper.
    A design that never touches it gets `assign analog_io = 29'hzzzzzzzz;` from
    yosys -- declaration plus a constant-Z tie, no behaviour. Excluding it
    fabricates nothing, and without this rule the gate can never judge the one
    artifact the external grader actually drives."""
    netlist = (
        "module top(clk, analog_io);\n"
        "  input clk;\n"
        "  inout [28:0] analog_io;\n"
        "  wire [28:0] analog_io;\n"
        "  assign analog_io = 29'hzzzzzzzz;\n"
        "endmodule\n")
    rails, inert, signals = gs.split_inouts(
        [gs.Port("analog_io", "inout", 29, 28, 0)], netlist)
    assert [p.name for p in inert] == ["analog_io"]
    assert signals == [] and rails == []


def test_an_inout_with_any_real_reference_still_vetoes():
    """One instance connection means the port participates in the design; the
    honest answer stays "cannot judge". Structural, not a name list: a design
    that actually drives its analog pads must not be blessed."""
    netlist = (
        "module top(clk, analog_io);\n"
        "  input clk;\n"
        "  inout [28:0] analog_io;\n"
        "  some_cell u0 (.pad(analog_io[3]));\n"
        "endmodule\n")
    rails, inert, signals = gs.split_inouts(
        [gs.Port("analog_io", "inout", 29, 28, 0)], netlist)
    assert inert == []
    assert [p.name for p in signals] == ["analog_io"]


def test_without_netlist_text_no_inout_is_presumed_inert():
    """No evidence, no exemption."""
    rails, inert, signals = gs.split_inouts(
        [gs.Port("analog_io", "inout", 29, 28, 0)])
    assert inert == [] and [p.name for p in signals] == ["analog_io"]


def test_driver_ties_power_rails_and_never_compares_them():
    ports = gs.parse_netlist_ports(_NETLIST_RAILS, "blk")
    cpp = gs.render_driver_cpp("blk", ports, "clk")
    assert "dut->vccd1 = 1;" in cpp
    assert "dut->vssd1 = 0;" in cpp
    # a rail carries no behaviour: it is never a recorded input nor a compared
    # output
    assert "dut->vccd1 = parse_scalar" not in cpp
    assert 'record("vccd1"' not in cpp and 'record("vssd1"' not in cpp


def test_power_only_boundary_is_judged_not_vetoed(monkeypatch, tmp_path):
    """A Caravel ``user_project_wrapper``'s only inouts are the eight supplies,
    and that wrapper is the artifact the external grader drives. Refusing on any
    ``inout`` made the gate structurally unable to judge it -- a hole exactly
    where the gate is supposed to be strongest."""
    net, pdk = _stub_env(monkeypatch, tmp_path, netlist=_NETLIST_RAILS)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 54, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_PASS
    assert res.detail["power_rails_tied"] == ["vccd1", "vssd1"]


def test_signal_tristate_boundary_still_has_no_honest_verdict(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path, netlist=_NETLIST_TRISTATE)
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_NOT_RUN
    assert "sda" in res.reason and "tri-state" in res.reason
    assert "vccd1" not in res.reason


# --------------------------------------------------------------------------- #
# debug mode -- see past the first divergence (opt-in, verdict unchanged)
# --------------------------------------------------------------------------- #
def test_default_driver_stops_at_the_first_divergence():
    cpp = gs.render_driver_cpp("blk", _ports(), "clk", debug=False)
    assert "if (div_cycle >= 0) break;" in cpp
    # the default verdict JSON must carry nothing extra
    assert "divergence_count" not in cpp
    assert "div_all" not in cpp
    # the verdict is still one JSON object with the two anti-blank counters and
    # the single first_divergence record
    assert "cycles_compared" in cpp and "output_bits_compared" in cpp
    assert "first_divergence" in cpp


def test_debug_driver_keeps_comparing_and_counts_them_all():
    cpp = gs.render_driver_cpp("blk", _ports(), "clk", debug=True,
                              max_divergences=5)
    assert "if (div_cycle >= 0) break;" not in cpp, "must not stop early"
    assert "div_count++;" in cpp
    assert "DIV_LIMIT = 5" in cpp
    assert "divergence_count" in cpp and "divergences" in cpp
    # first_divergence is still recorded exactly once, so the default report
    # text is unaffected
    assert "if (div_cycle >= 0) return;" in cpp


def test_debug_mode_is_read_from_the_env(monkeypatch):
    monkeypatch.setenv(gs.GATE_SIM_DEBUG_ENV, "1")
    monkeypatch.setenv("CORESMITH_GATE_SIM_MAX_DIVERGENCES", "7")
    cpp = gs.render_driver_cpp("blk", _ports(), "clk")
    assert "DIV_LIMIT = 7" in cpp
    monkeypatch.setenv(gs.GATE_SIM_DEBUG_ENV, "0")
    assert "DIV_LIMIT" not in gs.render_driver_cpp("blk", _ports(), "clk")


def test_debug_divergence_totals_reach_the_result(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 200000,
                      "output_bits_compared": 999, "diverged": True,
                      "first_divergence": {"cycle": 5151, "port": "q",
                                           "expected": "1010", "actual": "0000"},
                      "divergence_count": 1234,
                      "divergences": [{"cycle": 5151, "port": "q",
                                       "expected": "1010", "actual": "0000"}]},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert res.cycles_compared == 200000, "debug compares the whole stimulus"
    assert res.detail["divergence_count"] == 1234
    assert len(res.detail["divergences"]) == 1
    assert "1234 diverging port-cycles" in res.as_prev_error("blk")


def test_default_result_carries_no_divergence_total(monkeypatch, tmp_path):
    """Without debug the driver stopped at the first mismatch, so it does NOT
    know a total -- and must not imply one."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 5151,
                      "output_bits_compared": 999, "diverged": True,
                      "first_divergence": {"cycle": 5151, "port": "q",
                                           "expected": "1010", "actual": "0000"}},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "divergence_count" not in res.detail
    assert "diverging port-cycles" not in res.as_prev_error("blk")


# --------------------------------------------------------------------------- #
# fail-closed semantics
# --------------------------------------------------------------------------- #
def _stub_env(monkeypatch, tmp_path, *, netlist=_NETLIST):
    """Make check_gate_sim reach the reference-run stage on any host."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    pdk = tmp_path / "pdk" / "sky130A" / "libs.ref" / "sky130_fd_sc_hd" / "verilog"
    pdk.mkdir(parents=True)
    (pdk / "sky130_fd_sc_hd.v").write_text("// models\n")
    monkeypatch.setattr(gs, "macro_model_files", lambda *_a, **_k: ([], []))
    net = tmp_path / "net.v"
    net.write_text(netlist)
    return net, tmp_path / "pdk"


def test_missing_netlist_is_not_run_and_strict_makes_it_a_failure(monkeypatch, tmp_path):
    """No netlist on disk = nothing for THIS gate to judge (that is the synth
    gate's verdict), so it is a loud ``not_run`` -- and a hard FAIL under
    STRICT, where the caller demanded the gate really run."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "gone.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN and res.blocking is False
    assert "NO NETLIST" in res.reason
    monkeypatch.setenv("CORESMITH_GATE_SIM_STRICT", "1")
    res2 = gs.check_gate_sim(_BLOCK, str(tmp_path / "gone.v"), "r.v", "tb.py")
    assert res2.status == gs.STATUS_FAIL and res2.blocking


def test_empty_netlist_fails_closed(monkeypatch, tmp_path):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    net = tmp_path / "n.v"
    net.write_text("   \n")
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_FAIL


def test_wrong_top_in_netlist_fails_closed(monkeypatch, tmp_path):
    """A top the netlist does not declare is a FAIL, not a skip: there is an
    artifact on disk and it is not the design under test.

    The top is otherwise resolved from the netlist's STRUCTURE (the one module
    nothing instantiates), so the only way to name a missing top is an explicit
    ``block["top"]`` override -- which is exactly what this pins."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    res = gs.check_gate_sim({"name": "other", "top": "other",
                             "is_chip_top": True},
                            str(net), "r.v", "tb.py",
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "not found" in res.reason


def test_top_is_resolved_from_netlist_structure_not_the_block_name(monkeypatch,
                                                                  tmp_path):
    """The block's architectural name is not a stable key -- an external
    contract (a Caravel ``user_project_wrapper``) fixes the module name while the
    block keeps its own. Keying the gate off the block name made it FAIL CLOSED
    on a correctly synthesized netlist."""
    assert gs.resolve_netlist_top(_NETLIST) == "blk"
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 54, "diverged": False},
    )
    res = gs.check_gate_sim({"name": "totally_different_name",
                             "is_chip_top": True},
                            str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_PASS


def test_toolchain_check_precedes_the_netlist_verdict(monkeypatch, tmp_path):
    """The gate must only render a VERDICT where it could actually have run.
    With no simulator/PDK, even a missing netlist is ``not_run`` -- otherwise a
    PDK-free frontend host would fail every block on a gate it cannot execute
    (and, in the pipeline, spin the retry loop)."""
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    monkeypatch.setattr(gs.shutil, "which", lambda _n: None)
    res = gs.check_gate_sim(_BLOCK, str(tmp_path / "gone.v"), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.blocking is False

    # ...but a host WITH the toolchain and PDK does judge a missing netlist.
    monkeypatch.setattr(gs.shutil, "which", lambda _n: "/usr/bin/verilator")
    pdkdir = tmp_path / "pdk" / "sky130A" / "libs.ref" / "sky130_fd_sc_hd" / "verilog"
    pdkdir.mkdir(parents=True)
    (pdkdir / "sky130_fd_sc_hd.v").write_text("// models\n")
    net = tmp_path / "empty.v"
    net.write_text("   \n")
    res2 = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                             pdk_root=tmp_path / "pdk",
                             work_root=tmp_path / "work")
    assert res2.status == gs.STATUS_FAIL and res2.blocking


def test_absent_toolchain_is_not_run_not_pass(monkeypatch, tmp_path):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.delenv("CORESMITH_GATE_SIM_STRICT", raising=False)
    monkeypatch.setattr(gs.shutil, "which", lambda _n: None)
    net = tmp_path / "n.v"
    net.write_text(_NETLIST)
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.ran is False
    assert res.blocking is False


def test_absent_toolchain_under_strict_is_a_failure(monkeypatch, tmp_path):
    monkeypatch.setenv(gs.GATE_SIM_ENV, "1")
    monkeypatch.setenv("CORESMITH_GATE_SIM_STRICT", "1")
    monkeypatch.setattr(gs.shutil, "which", lambda _n: None)
    net = tmp_path / "n.v"
    net.write_text(_NETLIST)
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py")
    assert res.status == gs.STATUS_FAIL and res.blocking


def test_unmodellable_macro_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(gs, "macro_model_files", lambda *_a, **_k: ([], ["odd_macro"]))
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py", pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "odd_macro" in res.reason


def test_failed_reference_run_is_not_run(monkeypatch, tmp_path):
    """A reference that did not pass gives nothing trustworthy to compare
    against; that is an RTL/DV verdict, not a netlist verdict."""
    net, pdk = _stub_env(monkeypatch, tmp_path)

    def runner(*_a, **_k):
        return {"passed": False, "log": "boom"}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_NOT_RUN
    assert res.blocking is False


def test_reference_without_waveform_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)

    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(tmp_path / "absent.vcd")}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "no waveform" in res.reason


def test_zero_recorded_cycles_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    vcd = _write_vcd(tmp_path / "d.vcd", ["#0", "0!", "0#", "0%", "b0 &", "0("])

    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(vcd)}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "no clock cycles" in res.reason


def test_vacuous_stimulus_fails_closed(monkeypatch, tmp_path):
    """Outputs that never move across the whole run make the comparison
    meaningless -- that must not be scored as a gate-sim pass."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    lines = ["#0", "0!", "0#", "0%", "b0 &", "0("]
    t = 5
    for _ in range(6):
        lines += [f"#{t}", "1!", f"#{t + 5}", "0!"]
        t += 10
    vcd = _write_vcd(tmp_path / "d.vcd", lines)

    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(vcd)}

    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=runner, pdk_root=pdk,
                            work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "vacuous" in res.reason


def _good_ref(tmp_path):
    lines = ["#0", "0!", "0#", "0%", "b0 &", "0("]
    t = 5
    for i in range(6):
        lines += [f"#{t}", "1!", f"b{i % 2} &"]
        lines += [f"#{t + 5}", "0!"]
        t += 10
    return _write_vcd(tmp_path / "d.vcd", lines)


def _runner_for(vcd):
    def runner(*_a, **_k):
        return {"passed": True, "vcd_path": str(vcd)}
    return runner


def test_blank_verdict_fails_closed(monkeypatch, tmp_path):
    """The single most important property: a gate sim that produced no verdict
    must NEVER read as a pass."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": False, "stage": "verdict",
                      "error": "gate simulation produced no verdict file"},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "no verdict" in res.reason


def test_netlist_that_will_not_elaborate_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": False, "stage": "verilate",
                      "error": "the gate netlist did not elaborate/build"},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "elaborate" in res.reason


def test_zero_cycles_compared_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 0,
                      "output_bits_compared": 0, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "0 cycles" in res.reason


def test_zero_bits_compared_fails_closed(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 0, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL
    assert "0 output bits" in res.reason


def test_divergence_fails_closed_with_first_mismatch(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 4,
                      "output_bits_compared": 36, "diverged": True,
                      "first_divergence": {"cycle": 3, "port": "q",
                                           "expected": "00000001",
                                           "actual": "0"}},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_FAIL and res.blocking
    assert res.first_divergence["port"] == "q"
    report = res.as_prev_error("blk")
    assert "FIRST DIVERGENCE at cycle 3" in report
    assert "`ifdef" in report          # names the split-implementation cause


def test_matching_netlist_passes(monkeypatch, tmp_path):
    net, pdk = _stub_env(monkeypatch, tmp_path)
    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 54, "diverged": False},
    )
    res = gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py",
                            sim_runner=_runner_for(_good_ref(tmp_path)),
                            pdk_root=pdk, work_root=tmp_path / "work")
    assert res.status == gs.STATUS_PASS
    assert res.ran is True and res.ok is True and res.blocking is False
    assert res.cycles_compared == 6


def test_reference_run_is_isolated_and_seed_pinned(monkeypatch, tmp_path):
    """The reference must build in its OWN dir (never clobbering the block's DV
    build) under a PINNED seed, with the shallow port-only trace."""
    net, pdk = _stub_env(monkeypatch, tmp_path)
    seen = {}

    def runner(block, rtl_path, tb_path, attempt=1, extra_defines=None,
               sim_subdir=None, extra_args=None):
        import os as _os
        seen.update({"subdir": sim_subdir, "args": extra_args,
                     "defines": extra_defines,
                     "seed": _os.environ.get("CORESMITH_DV_SEED_PIN")})
        return {"passed": True, "vcd_path": str(_good_ref(tmp_path))}

    monkeypatch.setattr(
        gs, "build_and_run_gate_sim",
        lambda **_k: {"ok": True, "cycles_compared": 6,
                      "output_bits_compared": 54, "diverged": False},
    )
    monkeypatch.delenv("CORESMITH_DV_SEED_PIN", raising=False)
    gs.check_gate_sim(_BLOCK, str(net), "r.v", "tb.py", sim_runner=runner,
                      pdk_root=pdk, work_root=tmp_path / "work")
    assert seen["subdir"] == "blk__gatesim_ref"
    assert seen["args"] == ["--trace-depth 1"]
    assert seen["defines"] is None
    assert seen["seed"]
    # ...and the pin is restored afterwards
    import os as _os
    assert _os.environ.get("CORESMITH_DV_SEED_PIN") is None


def test_result_serializes_for_the_report(monkeypatch, tmp_path):
    res = gs.GateSimResult(ran=True, ok=False, status=gs.STATUS_FAIL,
                           reason="diverged", cycles_compared=3)
    blob = json.loads(json.dumps(res.as_dict()))
    assert blob["status"] == gs.STATUS_FAIL
    assert blob["cycles_compared"] == 3
